- name: "Copy helm yaml template for Galaxy."
  template:
    src: phenomenal-cerebellin-17.09-ingress.yaml.j2
    dest: ~/phenomenal-cerebellin-17.09-ingress.yaml

- name: add galaxy repo
  command: >
    helm repo add galaxy-helm-repo
    https://pcm32.github.io/galaxy-helm-charts

#- name: Delete if existing Galaxy objects
#  command: >
#      kubectl delete secrets/galaxy-admin-secret && kubectl delete configmaps/galaxy-admin-user &&
#      kubectl delete configmaps/db-connection &&
#      kubectl delete secrets/galaxy-postgres-secret

- name: install galaxy
  command: >
      helm upgrade --install -f ~/phenomenal-cerebellin-17.09-ingress.yaml
      --version "{{ galaxy_chart_version }}" "gs" galaxy-helm-repo/galaxy-stable
  no_log: "{{ nologging }}"

- name: expose proftpd on desired port
  command: >
    iptables -t nat -A PREROUTING -p tcp -i "{{ ansible_default_ipv4.interface }}" --dport "{{ proftpd_port }}"
          -j REDIRECT --to-ports 30722
  become: yes
  no_log: "{{ nologging }}"
