---
- name: Installs phenomenal services
  hosts: master
  gather_facts: "yes"
  vars:
    # Services
    galaxy_include: "true"
    galaxy_hostname: "galaxy"
    galaxy_generated_key: "{{lookup('password', 'galaxy-api-key length=25 chars=ascii_letters')}}"
    # Storage
    pvc_name: "galaxy-pvc"
    # Domain
    cloudflare_proxied: "false"
    proxied_suffix: ""
    # Logging
    no_sensitive_logging: "false"

  tasks:
    # Galaxy
    - name: Galaxy
      include_role:
        name: roles/galaxy
      vars:
        hostname: "{{galaxy_hostname}}{{proxied_suffix}}"
        galaxy_admin_password: "generate-random-passw"
        galaxy_admin_email: "your @ email.com"
        galaxy_api_key: "{{galaxy_generated_key}}"
        galaxy_pvc: "{{pvc_name}}"
        postgres_pvc: "{{pvc_name}}"
        nologging: "{{no_sensitive_logging}}"
      when:
        galaxy_include | bool  == true
