---
  hosts: master
  gather_facts: "yes"

  tasks:
    # Galaxy
    - name: Galaxy
      include_role:
        name: roles/galaxy
      vars:
        hostname: "{{galaxy_hostname}}"
        galaxy_image_tag: "dev_v17.09-pheno-lr_cv1.6.190"
        galaxy_admin_password: "{{galaxy_admin_password}}"
        galaxy_admin_email: "{{galaxy_admin_email}}"
        galaxy_api_key: "{{galaxy_api_key}}"
        galaxy_pvc: "{{galaxy_pvc}}"
        postgres_pvc: "{{galaxy_pvc}}"
        nologging: "{{galaxy_nologging}}"
